// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectCompletionReport.Services;

#nullable disable

namespace ProjectCompletionReport.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectCompletionReport.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("AdministrativeMinistryDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Budget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutingAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MajorActivities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallObjective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanningCommissionSectorDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonsForNoCostTimeExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonsForRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificObjectives")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._06LocationOfTheProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityCorpMunicipalityUpazila")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("_06LocationOfTheProjects");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._07EstimatedCostPeriodApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImplementationPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SelfFinance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Total")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_07EstimatedCostPeriodApprovals");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._12_1aStatusOfLoanGrantForeignFinancing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AmountInUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyAsPerAgreement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfAgreement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfEffectiveness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalDateOfClosing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RevisedDateOfClosing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_12_1aStatusOfLoanGrantForeignFinancings");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._12_1bStatusOfLoanGrantGOB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CashForeignExchange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("TotalAmount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_12_1bStatusOfLoanGrantGOBs");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._12_1cStatusOfLoanGrantSelfFinanceEquity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CashForeignExchange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SelfFinance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalAmount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_12_1cStatusOfLoanGrantSelfFinanceEquities");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._12_2UtilizationOfProjectAid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualExpenditureInLocalCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualExpenditureInUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalAmountInLocalCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalAmountInUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnutilizedAmountInLocalCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnutilizedAmountInUSD")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_12_2UtilizationOfProjectAids");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._12_3ReimbursableProjectAid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AmountClaimed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmountReimbursed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmountSpent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RPAAmountAsPerAgreement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RPAAmountAsPerPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_12_3ReimbursableProjectAids");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._13ImplementationPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualImplementation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestRevised")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Original")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeOverRun")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_13ImplementationPeriods");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._14CostOfTheProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualExpenditure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostOverRun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestRevisedEstimatedCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalEstimatedCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_14CostOfTheProjects");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._15InfoProjectDirector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Joining")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAndDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibleForMoreThanOneProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transfer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_15InfoProjectDirectors");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._16Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("TotalApprovedStrength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalEmployedDuringImplementation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalNameOfPost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalNameOfPostGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalReasonForNotRecruited")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalRecruited")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_16Personnels");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._16_1PersonnelOfPIU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedStrength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployedDuringImplementation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfPost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("_16_1PersonnelOfPIUs");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._16_2PersonnelRequiredAfterCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameOfPost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForNotRecruited")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recruited")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_16_2PersonnelRequiredAfterCompletions");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._17TrainingForeignLocal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchAchievement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchAsInPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DWMAchievement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DWMAsInPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParticipantAchievement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParticipantAsInPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SlNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_17TrainingForeignLocals");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._17_18Total", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SubTotalCapital_ActualGOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalCapital_ActualOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalCapital_ActualPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalCapital_ActualSelfFinance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalCapital_ActualTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalCapital_EstimatedGOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalCapital_EstimatedOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalCapital_EstimatedPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalCapital_EstimatedSelfFinance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalCapital_EstimatedTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalForeign_BatchAchievement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalForeign_BatchAsInPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalForeign_DWMAchievement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalForeign_DWMAsInPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalForeign_ParticipantAchievement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalForeign_ParticipantAsInPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalLocal_BatchAchievement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalLocal_BatchAsInPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalLocal_DWMAchievement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalLocal_DWMAsInPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalLocal_ParticipantAchievement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalLocal_ParticipantAsInPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalRevenue_ActualGOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalRevenue_ActualOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalRevenue_ActualPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalRevenue_ActualSelfFinance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalRevenue_ActualTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalRevenue_EstimatedGOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalRevenue_EstimatedOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalRevenue_EstimatedPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalRevenue_EstimatedSelfFinance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalRevenue_EstimatedTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalLocalForeign_BatchAchievement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalLocalForeign_BatchAsInPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalLocalForeign_DWMAchievement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalLocalForeign_DWMAsInPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalLocalForeign_ParticipantAchievement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalLocalForeign_ParticipantAsInPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalRevenueCapital_ActualGOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalRevenueCapital_ActualOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalRevenueCapital_ActualPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalRevenueCapital_ActualSelfFinance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalRevenueCapital_ActualTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalRevenueCapital_EstimatedGOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalRevenueCapital_EstimatedOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalRevenueCapital_EstimatedPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalRevenueCapital_EstimatedSelfFinance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalRevenueCapital_EstimatedTotal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_17_18Totals");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._18ComponentWiseProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualGOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualSelfFinance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedGOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedSelfFinance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfComponent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_18ComponentWiseProgresses");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._19ProcurementOfTransport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CondemnedDamaged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondemnedDamagedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberAsPerProjectDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberProcured")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberProcuredDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnedToFollowingProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnedToFollowingProjectDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferredToOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferredToOMDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferredToTransferPool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferredToTransferPoolDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfTransport")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_19ProcurementOfTransports");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._20ProjectConsultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualManMonthUtilized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedManMonthAsPerContract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedManMonthAsPerPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfTheField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfDeliverablesActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfDeliverablesAsPerPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_20ProjectConsultants");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._21InfrastructureErectionInstallation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Balance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisposedOff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisposedOffDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("QuantityAsPerProjectDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuantityProcured")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuantityProcuredDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferredToOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferredToOMDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_21InfrastructureErectionInstallations");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._22_1InfoOnPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GoodsAsPerPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodsMoreThanOnePct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodsProcured")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForNotProcuring")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServicesAsPerPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServicesMoreThanOnePct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServicesProcured")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalPackagesAsPerPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalPackagesMoreThanOnePct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalPackagesProcured")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorksAsPerPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorksMoreThanOnePct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorksProcured")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_22_1InfoOnPackages");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._23OriginalAndRevisedProvisionTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FinancialYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GOBOriginal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GOBRevised")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersOriginal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersRevised")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAOriginal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PARevised")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalPercentageOriginal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalPercentageRevised")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SelfFinanceOriginal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelfFinanceRevised")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalOriginal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalRevised")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_23OriginalAndRevisedProvisionTargets");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._24RevisedADPAllocationAndProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FinancialYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GOBAllocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GOBProgress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GOBRelease")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersAllocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersProgress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAAllocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAProgress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalPercentageAllocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalPercentageProgress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SelfFinanceAllocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelfFinanceProgress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalAllocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalProgress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnspentGOBReleased")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_24RevisedADPAllocationAndProgresses");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._25ObjectiveAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achievement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonsForShortfall")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_25ObjectiveAchievements");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._26AnnualOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualQuantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedQuantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_26AnnualOutputs");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._27CostBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Actual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estimated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("_27CostBenefits");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._29Monitoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentifiedProblems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAndDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Recommendations")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_29Monitorings");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._30Auditing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("TotalExternalMajorFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalExternalWhetherResolved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalInternalMajorFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalInternalWhetherResolved")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_30Auditings");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._30_1InternalAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MajorFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmissionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhetherObjectionsResolved")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_30_1InternalAudits");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._30_2ExternalAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MajorFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmissionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhetherObjectionsResolved")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_30_2ExternalAudits");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._Annex1A_ProcurementOfGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualApprovingAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDateOfApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDateOfNOA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDateOfOpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDateOfTenderInvitation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualEstimatedCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualPayment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualProcurementMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionDateActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionDateAsPerContract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionOfPackage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationApprovingAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationDateOfApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationDateOfNOA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationDateOfOpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationDateOfTenderInvitation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationEstimatedCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationProcurementMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfNewspaper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanApprovingAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanDateOfApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanDateOfNOA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanDateOfOpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanDateOfTenderInvitation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanEstimatedCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanProcurementMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("_Annex1A_ProcurementOfGoods");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._Annex1B_ProcurementOfWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualApprovingAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDateOfApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDateOfNOA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDateOfOpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDateOfTenderInvitation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualEstimatedCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualPayment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualProcurementMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionDateActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionDateAsPerContract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionOfPackage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationApprovingAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationDateOfApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationDateOfNOA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationDateOfOpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationDateOfTenderInvitation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationEstimatedCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationProcurementMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfNewspaper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanApprovingAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanDateOfApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanDateOfNOA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanDateOfOpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanDateOfTenderInvitation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanEstimatedCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanProcurementMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("_Annex1B_ProcurementOfWorks");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._Annex1C_ProcurementOfService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualApprovingAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDateOfApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDateOfNOA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDateOfOpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDateOfTenderInvitation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualEstimatedCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualPayment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualProcurementMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionDateActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionDateAsPerContract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionOfPackage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationApprovingAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationDateOfApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationDateOfNOA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationDateOfOpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationDateOfTenderInvitation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationEstimatedCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationProcurementMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfNewspaper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanApprovingAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanDateOfApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanDateOfNOA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanDateOfOpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanDateOfTenderInvitation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanEstimatedCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanProcurementMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("_Annex1C_ProcurementOfServices");
                });

            modelBuilder.Entity("ProjectCompletionReport.Models._G_PostProjectRemark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Appraisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Concept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditAgreement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditEffectiveness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditNegotiation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Design")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JustificationAdequacy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanDisbursement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objectives")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersSpecify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectIdentification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectPreparation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectRevisionWithReasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_28ReasonsForShortFall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_34_9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_35_9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_36DateAH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_36DatePD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_36DateSec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_36RemarksAH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_36RemarksPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_36RemarksSec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("_36SealAH")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("_36SealPD")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("_36SealSec")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("_36SignAH")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("_36SignPD")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("_36SignSec")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("_G_PostProjectRemarks");
                });
#pragma warning restore 612, 618
        }
    }
}
